default_context:
  name: "pipupgrade"
  version: "1.10.1"
  slug: "pipupgrade"
  command: "pipupgrade"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "n"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "UPGRADE ALL THE PIP PACKAGES!"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "pip update upgrade cli command"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "pipupgrade"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "pipupgrade"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/pipupgrade"