language: python
sudo: true

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - ENVIRONMENT=test
    - VENVDIR=$VIRTUAL_ENV
    - VERBOSE=true

install:
  - . $TRAVIS_BUILD_DIR/ci/scripts/install.sh
  - make install

script:
  - make test

after_success:
  - make coverage