language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  global:
    - ENVIRONMENT=test
    - VERBOSE=true
    - secure: VJs9MZAeYdBXxE1ePMe9UT7weaj6phvTisSk/Esz6/9QOeTUSdsMW/NuWce2DRagqa0glKc4Eur4bRBLNcx7xQ4uHmKsEOCu86GOumuZ4Z3g0zPqEf+SoCMczURjD+XsIvs5V7agoA1M0FCOWl6WfCEMRoFExfFdI8BCz6F0EYV/6Z5PYrEsuVxsDpF/hVoDzrtMO1lRKUVg3utf1HDYGuch613sjI7GU3sKKQpb9eR/4pUgQwfEgcPDfsqgYcJ4+JTPqrcBz8P5S/XJEfOXGg/B9MpZVccQj/hWHHXPEiAJNfGLsP1iTmhbYF4cGrEMxmmuXL5Y2Q0IvDb5Sp1OKS580eFkcbjWQupXqKEOZk//5ac8GdxjrDZSIilZRS2Even9O4FnzAvWnY+7tEbn47PMintxhI5IryxC/mJ66cOmhBgzBCESqxGIw0dOZdMDsrMlnLQV8V+RYpLs9udNU/skzbBCnyZzGp7+0kcCS8l2U6CSbpkUHYbSTNmbveFpDmS98n0tUL+m01qGY+UmQFXcbXq8NbKYMX227XYKmCK0GU1z3SRWfaX99xmJG+tgCWrD+VihBvBv+cuXTl1u32/UBmEhrm2AZM+Hz9m/9D4IGa58l+KjxVVd2Qxqq1MWRRK55wazbWiCR77WAlDXiZxFpVwZrqalJ3S0DtmrS5I=

install:
  - sudo $TRAVIS_BUILD_DIR/ci/scripts/bash/install.sh
  - VENVDIR=$VIRTUAL_ENV make install

script:
  - VENVDIR=$VIRTUAL_ENV make test

after_success:
  - VENVDIR=$VIRTUAL_ENV make coverage
  - npx semantic-release