language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - ENVIRONMENT=test VENVDIR=$VIRTUAL_ENV VERBOSE=true

install:
  - make install

script:
  - make test

after_success:
  - make coverage