name: Template

on:
  push:
  
jobs:
  template:
    name: Template
    runs-on: ubuntu-latest
    steps:
      - uses: achillesrasquinha/boilpy-action@0.1.0-beta
      - name: Updating template
        run: |
          echo "Updating template..."