name: Continuous Integration

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  ENVIRONMENT: test
  VERBOSE: true
  TERM: xterm

  PYTEST_ADDOPTS: "--color=yes"

  PYTHON: python
  PIP: pip
  PYTEST: pytest
  COVERALLS: coveralls

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade PIP and packages
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          make install
      - name: Run Tests
        run: |
          make coverage